### ISSUE TITLE
makedsig - do not remove duplicates

### ISSUE THREAD

**Issue by lab313ru** [nemerle/dcc#23]
When generating sig-file it will be better to use on of duplicated records instead of removing both of them.

Or, if it works that way already, allow to choose which of duplicates to use.

**Comment by nemerle** [comment]
The dcc will not have any ability to properly know which function it found, thus decompilation result will be wrong - discarding both duplicates is the right move in that case

**Comment by lab313ru** [comment]
You didn't understand. I mean the same signatures for some lib-functions. One of two duplicated items we should use anyway.

As I found, makedsig uses first item in every case.

**Comment by lab313ru** [comment]
Hmm, bad idea. Prompting at every duplicate is very long procedure to generate then.
