### ISSUE TITLE
Use of malloc.h

### ISSUE THREAD

**Issue by Godzil** [nemerle/dcc#28]
Some files (like pasehdr.cpp, makedsig.cpp and control.cpp) use the windows only malloc.h header file.
On UNIX-y Linux or Mac OS X, this header is non existent as malloc is normally defined in stdlib.h

I never understood why Microsoft have done that, but it would be nice to explicitely not try to add the malloc.h file if trying to compile on another system than Windows

A simple 

#ifdef WIN32
#include <malloc.h>
#endif

should be enough

**Comment by nemerle** [comment]
I don't think those includes are needed/used anyway, will remove them outright, thanks.
