### ISSUE TITLE
What is the license of DCC?

### ISSUE THREAD

**Issue by geraldo-netto** [nemerle/dcc#31]
Dear Friends,

Could you clarify me what is the license of DCC?
I would like to add DCC on [FreeDOS](http://www.freedos.org/)
But we need to make sure DCC is opensource

Thank You Very Much/Kind Regards,
Geraldo Netto

**Comment by nemerle** [comment]
The original release had GPL, so I've added it here as well, thanks for the reminder :)

**Comment by geraldo-netto** [comment]
Hey @nemerle,

Thank You Very Much, we are discussing the inclusion of DCC on FreeDOS user mailing list! :)
https://www.mail-archive.com/freedos-user@lists.sourceforge.net/

Kind Regards,
Geraldo Netto
