### ISSUE TITLE
can't get this to build

### ISSUE THREAD

**Issue by Strugglemeat** [nemerle/dcc#34]
I've tried with several different borland compilers in dosbox. can anyone provide a step-by-step guide on how to compile this?

**Comment by nemerle** [comment]
Ahh, I think the original readme I've added is a bit misleading.

The project should be built using CMake and a modern compiler ( MSVC/gcc/clang ).

**Comment by Strugglemeat** [comment]
ok, I used "cmake ." and then "make" and got an error about adding `#include <cstddef>` to idioms/idiom1.h
just got a successful compile, testing

**Comment by Strugglemeat** [comment]
> ./dcc_original MAIN.EXE
> Model: m
> Borland v3 detected
> Signature file: dccb3m.sig
> Wanted to start interactive disasassembler for  "proc_010eaa_51" : 29
> dcc_original: /home/username/Downloads/dcc-qt5/src/scanner.cpp:579: eErrorId scan(uint32_t, ICODE&): Assertion `p.ll()->numBytes == p.insn.size' failed.
> Aborted (core dumped)
> 

another try, different executable:

> ./dcc_original T2B.EXE 
> Model: l
> Borland v3 detected
> Signature file: dccb3l.sig
> Warning: cannot open signature file /home/username/Downloads/dcc-qt5/sigs/dccb3l.sig
> Wanted to start interactive disasassembler for  "proc_013e6c_27" : 87
> Wanted to start interactive disasassembler for  "proc_002739_45" : 0
> Segmentation fault (core dumped)

**Comment by nemerle** [comment]
This tool was created a long, long time ago, and needs some serious amount of work to be something that can be used on 'random' 16-bit executables 

My suggestion would be to see if `ghidra` or `reko` will not work better for You :smile:

**Comment by Strugglemeat** [comment]
ok, thanks
