### ISSUE TITLE
--output option doesn't work

### ISSUE THREAD

**Issue by lab313ru** [nemerle/dcc#9]
Subj.

**Comment by lab313ru** [comment]
Maybe because of not correct option specifying by me.

**Comment by nemerle** [comment]
So far this option seems to work - please re-test and close this ticket ?

Target file option ("--output") gives the name for the resulting assembly files ( .a1 and .a2 ) not for the final .b  file.

If you need this kind of functionality, please consider adding a new enhancement ticket.

**Comment by lab313ru** [comment]
Could you give me command line as example how to use this option? When I will be able to run some of test files in DCC, I'll test it, and check then.

For now, we can close it.

**Comment by lab313ru** [comment]
VS Release version compiled seems to work.
